---
version: "3.7"

volumes:
  nextcloud-app-config:
  nextcloud-app-data:
  nextcloud-mariadb:

services:
  nextcloud-app-config-s3: # name given to service
    image: elementar/s3-volume
    container_name: nextcloud-app-config-s3 # name given to container
    command: /data s3://nextcloud-app-config # s3 bucket name
    env_file:
      - .env.volume
    volumes:
      - nextcloud-app-config:/data # app configs

  nextcloud-app-data-s3:
    image: elementar/s3-volume
    container_name: nextcloud-app-data-s3
    command: /data s3://nextcloud-app-data
    env_file:
      - .env.volume
    volumes:
      - nextcloud-app-data:/data # personal data

  nextcloud-mariadb-s3:
    image: elementar/s3-volume
    container_name: nextcloud-mariadb-s3
    command: /data s3://nextcloud-mariadb
    env_file:
      - .env.volume
    volumes:
    - nextcloud-mariadb:/data

  nextcloud-app:
    image: lscr.io/linuxserver/nextcloud
    container_name: nextcloud-app
    env_file:
       - .env.app
    volumes:
      - nextcloud-app-config:/config
      - nextcloud-app-data:/data
    ports:
      - 4433:443
    restart: unless-stopped
    depends_on:
      - nextcloud-app-config-s3 # volume proxy container
      - nextcloud-app-data-s3   # [...]
      - nextcloud-mariadb-s3
      - nextcloud-mariadb       # actual service container

  nextcloud-mariadb:
    image: lscr.io/linuxserver/mariadb
    container_name: nextcloud-mariadb
    env_file:
      - .env.mariadb
    volumes:
      - nextcloud-mariadb:/config
    restart: unless-stopped
    depends_on:
      - nextcloud-mariadb-s3
